#source 'https://rubygems.org'
source 'https://gems.ruby-china.com'

gem 'pg'
gem 'sinatra-namespace'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord', path: ".."
gem 'activerecord', '>= 4.1'
gem 'pry'
gem 'pry-byebug'
